# **Objective**:

- Use TF-IDF with different feature limits to compare performance.
- Train and evaluate a Logistic Regression model
- Handle class imbalance using class weights.

##Import Necessary Libraries

In [ ]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():

    # Tell PyTorch to use the GPU.
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla T4

In [ ]:
pip install livelossplot

Collecting livelossplot
  Downloading livelossplot-0.5.6-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from livelossplot) (3.10.0)
Requirement already satisfied: bokeh in /usr/local/lib/python3.11/dist-packages (from livelossplot) (3.7.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (1.3.2)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (1.38.2)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (2.0.2)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (24.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (2.2.2)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (11.2.1)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (6.0.2)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (6.4.2)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.11/dist-packages (from bokeh->livelossplot) (2025.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->livelossplot) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->livelossplot) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->livelossplot) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->livelossplot) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->livelossplot) (2.9.0.post0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2>=2.9->bokeh->livelossplot) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->bokeh->livelossplot) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->bokeh->livelossplot) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->livelossplot) (1.17.0)
Downloading livelossplot-0.5.6-py3-none-any.whl (23 kB)
Installing collected packages: livelossplot
Successfully installed livelossplot-0.5.6

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, accuracy_score, classification_report
from sklearn.naive_bayes import ComplementNB
from sklearn.pipeline import Pipeline
import joblib

In [ ]:
!pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.18.0)
Collecting tensorflow
  Downloading tensorflow-2.19.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.13.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.71.0)
Collecting tensorboard~=2.19.0 (from tensorflow)
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.13.0)
Collecting ml-dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.0.9)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Downloading tensorflow-2.19.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (644.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.9/644.9 MB 2.9 MB/s eta 0:00:00
Downloading ml_dtypes-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 89.1 MB/s eta 0:00:00
Downloading tensorboard-2.19.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 89.5 MB/s eta 0:00:00
Installing collected packages: ml-dtypes, tensorboard, tensorflow
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.4.1
    Uninstalling ml-dtypes-0.4.1:
      Successfully uninstalled ml-dtypes-0.4.1
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.18.0
    Uninstalling tensorboard-2.18.0:
      Successfully uninstalled tensorboard-2.18.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.18.0
    Uninstalling tensorflow-2.18.0:
      Successfully uninstalled tensorflow-2.18.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.19.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.19.0 which is incompatible.
tensorflow-decision-forests 1.11.0 requires tensorflow==2.18.0, but you have tensorflow 2.19.0 which is incompatible.
Successfully installed ml-dtypes-0.5.1 tensorboard-2.19.0 tensorflow-2.19.0

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
from keras import Model, Input
from keras.layers import LSTM, Embedding, Dense
from keras.layers import TimeDistributed, SpatialDropout1D, Bidirectional
from keras.callbacks import ModelCheckpoint, EarlyStopping
from livelossplot.tf_keras import PlotLossesCallback

##Load Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_cleaned = pd.read_csv("/content/drive/MyDrive/Arabic_Dialect_Classification/cleaned_dataset.csv", engine="python")

In [ ]:
df_cleaned

,Cleaned_text,SpeakerDialect
0,وضح كلامك يا مغيث,Najdi
1,تري راسي ما عاد يتحمل الغازك,Najdi
2,سلامه راسك يا ابو مسامح,Najdi
3,ما يصير يا ابو مسامح تخلي البنت في البيت دون ...,Najdi
4,ويش فيها لقعدت في البيت دون امها ما هو ده بيت...,Najdi
...,...,...
241828,لازم تشيلها عشان تصير سعيد في حياتك,Najdi
241829,انا سويت كل هذا علي شانك لا واله مريم مريم عط...,More than 1 speaker اكثر من متحدث
241830,مريم,Najdi
241831,لا لا,Najdi
241832,مريم لا لا,Najdi

In [ ]:
pd.set_option('display.max_rows',500)
pd.set_option('display.max_colwidth',500)

In [ ]:
df_cleaned.isnull().values.any()

np.False_

In [ ]:
df_cleaned.isnull().sum()

Cleaned_text      0
SpeakerDialect    0
dtype: int64

##Data Splitting

In [ ]:
x=df_cleaned.drop(['SpeakerDialect'], axis=1)
y=df_cleaned['SpeakerDialect']

In [ ]:
print("shape of x :",x.shape)
print("shape of y  :" ,y.shape)

shape of x : (241833, 1)
shape of y  : (241833,)

In [ ]:
x_train ,x_test ,y_train , y_test = train_test_split(x,y,test_size=0.15, random_state=24, shuffle=True,stratify=y)

In [ ]:
x_train, x_val , y_train, y_val = train_test_split(x_train, y_train, test_size=0.10, random_state=42,stratify=y_train)

In [ ]:
x_train.isnull().sum()

Cleaned_text    0
dtype: int64

# Tokenizer and Model

## ML Models

We extract all **unique words** from the `Cleaned_text` column of the training set using a Python `set`. This helps us:

- Get an understanding of the vocabulary size.
- Prepare for building the tokenizer or embedding layer.

Steps:
1. Iterate over each cleaned text sample.
2. Tokenize by splitting on whitespace.
3. Add tokens to a set, which automatically filters duplicates.

The final count gives us the **number of distinct words** present in the training data.

In [ ]:
# Use a Set to Store Unique Words
unique_words = set()

for text in x_train['Cleaned_text']:
    words = text.split()  # Tokenize
    unique_words.update(words)

# Number of Unique Words
num_unique_words = len(unique_words)
print(f'Number of unique words: {num_unique_words}')

Number of unique words: 135637

**Term Frequency-Inverse Document Frequency (TF-IDF):**
-  TF-IDF assigns weights to terms based on their frequency in individual documents and their inverse frequency across all documents. This technique helps capture the importance of terms in distinguishing between documents.

In [ ]:
# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=5000)
x_train_tfidf = vectorizer.fit_transform(x_train['Cleaned_text'])
x_val_tfidf = vectorizer.transform(x_val['Cleaned_text'])
x_test_tfidf = vectorizer.transform(x_test['Cleaned_text'])

In [ ]:
# Initialize LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_val_encoded = label_encoder.transform(y_val)
y_test_encoded = label_encoder.transform(y_test)

In [ ]:
# Check the mapping
print("Label Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

Label Mapping: {'Egyptian': np.int64(0), 'Hijazi': np.int64(1), 'Iraqi': np.int64(2), 'Janubi': np.int64(3), 'Khaliji': np.int64(4), 'Levantine': np.int64(5), 'Maghrebi': np.int64(6), 'ModernStandardArabic': np.int64(7), 'More than 1 speaker اكثر من متحدث': np.int64(8), 'Najdi': np.int64(9), 'Notapplicable': np.int64(10), 'Shamali': np.int64(11), 'Unknown': np.int64(12), 'Yemeni': np.int64(13)}

##Logistic regression

In [ ]:
# Train a Logistic Regression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(x_train_tfidf, y_train_encoded)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
# Evaluate on validation set
y_val_pred = model.predict(x_val_tfidf)
val_accuracy = accuracy_score(y_val_encoded, y_val_pred)
print(f'Validation Accuracy: {val_accuracy:.4f}')

Validation Accuracy: 0.5198

In [ ]:
# Evaluate on test set
y_test_pred = model.predict(x_test_tfidf)
test_accuracy = accuracy_score(y_test_encoded, y_test_pred)
print(f'Test Accuracy: {test_accuracy:.4f}')

Test Accuracy: 0.5232

In [ ]:
from sklearn.metrics import classification_report

# Get full label range
labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# Print classification report
print(classification_report(
    y_test_encoded,
    y_test_pred,
    labels=labels,
    target_names=target_names,
    zero_division=0  # Avoids division-by-zero warnings
))

                                   precision    recall  f1-score   support

                         Egyptian       0.50      0.05      0.09       305
                           Hijazi       0.43      0.29      0.35      5225
                            Iraqi       0.00      0.00      0.00         0
                           Janubi       0.00      0.00      0.00        15
                          Khaliji       0.34      0.11      0.17      4274
                        Levantine       0.50      0.01      0.01       142
                         Maghrebi       0.00      0.00      0.00         6
             ModernStandardArabic       0.50      0.18      0.27       614
More than 1 speaker اكثر من متحدث       0.64      0.66      0.65      7520
                            Najdi       0.51      0.81      0.63     13599
                    Notapplicable       0.00      0.00      0.00        58
                          Shamali       0.00      0.00      0.00        19
                          Unknown       0.48      0.19      0.28      4441
                           Yemeni       0.00      0.00      0.00        57

                         accuracy                           0.52     36275
                        macro avg       0.28      0.16      0.17     36275
                     weighted avg       0.50      0.52      0.48     36275

### use 10000  Unique Words

In [ ]:
# TF-IDF Vectorization
vectorizer_ = TfidfVectorizer(max_features=10000)
x_train_tfidf = vectorizer_.fit_transform(x_train['Cleaned_text'])
x_val_tfidf = vectorizer_.transform(x_val['Cleaned_text'])
x_test_tfidf = vectorizer_.transform(x_test['Cleaned_text'])

In [ ]:
# Train a Logistic Regression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(x_train_tfidf, y_train_encoded)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
# Evaluate on validation set
y_val_pred = model.predict(x_val_tfidf)
val_accuracy = accuracy_score(y_val_encoded, y_val_pred)
val_Precision = precision_score(y_val_encoded, y_val_pred, average='macro')
print(f'Validation Accuracy: {val_accuracy:.4f}')
print(f'Precision: {val_Precision:.4f}')

Validation Accuracy: 0.5218
Precision: 0.2651

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Evaluate on test set
y_test_pred = model.predict(x_test_tfidf)
test_accuracy = accuracy_score(y_test_encoded, y_test_pred)
print(f'Test Accuracy: {test_accuracy:.4f}')

Test Accuracy: 0.5262

In [ ]:
from sklearn.metrics import classification_report

# Get full label range
labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# Print classification report
print(classification_report(
    y_test_encoded,
    y_test_pred,
    labels=labels,
    target_names=target_names,
    zero_division=0  # Avoids division-by-zero warnings
))

                                   precision    recall  f1-score   support

                         Egyptian       0.57      0.05      0.10       305
                           Hijazi       0.43      0.31      0.36      5225
                            Iraqi       0.00      0.00      0.00         0
                           Janubi       0.00      0.00      0.00        15
                          Khaliji       0.34      0.12      0.18      4274
                        Levantine       0.50      0.03      0.05       142
                         Maghrebi       0.00      0.00      0.00         6
             ModernStandardArabic       0.53      0.18      0.27       614
More than 1 speaker اكثر من متحدث       0.63      0.65      0.64      7520
                            Najdi       0.52      0.81      0.63     13599
                    Notapplicable       0.00      0.00      0.00        58
                          Shamali       0.00      0.00      0.00        19
                          Unknown       0.48      0.21      0.29      4441
                           Yemeni       0.00      0.00      0.00        57

                         accuracy                           0.53     36275
                        macro avg       0.29      0.17      0.18     36275
                     weighted avg       0.50      0.53      0.49     36275

Use All Unique Words

In [ ]:
# TF-IDF Vectorization
vectorizer_ = TfidfVectorizer(max_features=num_unique_words)
x_train_tfidf = vectorizer_.fit_transform(x_train['Cleaned_text'])
x_val_tfidf = vectorizer_.transform(x_val['Cleaned_text'])
x_test_tfidf = vectorizer_.transform(x_test['Cleaned_text'])

In [ ]:
# Train a Logistic Regression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(x_train_tfidf, y_train_encoded)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
# Evaluate on validation set
y_val_pred = model.predict(x_val_tfidf)
val_accuracy = accuracy_score(y_val_encoded, y_val_pred)
val_Precision = precision_score(y_val_encoded, y_val_pred, average='macro')
print(f'Validation Accuracy: {val_accuracy:.4f}')
print(f'Precision: {val_Precision:.4f}')

Validation Accuracy: 0.5208
Precision: 0.2567

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Evaluate on test set
y_test_pred = model.predict(x_test_tfidf)
test_accuracy = accuracy_score(y_test_encoded, y_test_pred)
print(f'Test Accuracy: {test_accuracy:.4f}')

Test Accuracy: 0.5271

In [ ]:
from sklearn.metrics import classification_report

# Get full label range
labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# Print classification report
print(classification_report(
    y_test_encoded,
    y_test_pred,
    labels=labels,
    target_names=target_names,
    zero_division=0  # Avoids division-by-zero warnings
))

                                   precision    recall  f1-score   support

                         Egyptian       0.46      0.04      0.07       305
                           Hijazi       0.45      0.32      0.37      5225
                            Iraqi       0.00      0.00      0.00         0
                           Janubi       0.00      0.00      0.00        15
                          Khaliji       0.36      0.14      0.20      4274
                        Levantine       0.33      0.02      0.04       142
                         Maghrebi       0.00      0.00      0.00         6
             ModernStandardArabic       0.57      0.18      0.28       614
More than 1 speaker اكثر من متحدث       0.60      0.64      0.62      7520
                            Najdi       0.53      0.80      0.64     13599
                    Notapplicable       0.00      0.00      0.00        58
                          Shamali       0.00      0.00      0.00        19
                          Unknown       0.51      0.23      0.31      4441
                           Yemeni       0.00      0.00      0.00        57

                         accuracy                           0.53     36275
                        macro avg       0.27      0.17      0.18     36275
                     weighted avg       0.51      0.53      0.49     36275

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Get unique classes
classes = np.unique(y_train_encoded)

# Compute weights
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train_encoded)

# Make dict: {class_index: weight}
class_weight_dict = dict(zip(classes, weights))

# Train model
model = LogisticRegression(class_weight=class_weight_dict, max_iter=1000, random_state=42)
model.fit(x_train_tfidf, y_train_encoded)

LogisticRegression(class_weight={np.int64(0): np.float64(8.508968816116273),
                                 np.int64(1): np.float64(0.4959068026955594),
                                 np.int64(2): np.float64(6607.214285714285),
                                 np.int64(3): np.float64(167.27124773960216),
                                 np.int64(4): np.float64(0.6063055091272572),
                                 np.int64(5): np.float64(18.22679802955665),
                                 np.int64(6): np.float64(412.95089285714283),
                                 np.int64(7): np.float64(4.223211432223896),
                                 np.int64(8): np.float64(0.34455643959711546),
                                 np.int64(9): np.float64(0.19054142016709788),
                                 np.int64(10): np.float64(44.34372003835091),
                                 np.int64(11): np.float64(134.8411078717201),
                                 np.int64(12): np.float64(0.5833669685426704),
                                 np.int64(13): np.float64(45.88343253968254)},
                   max_iter=1000, random_state=42)

In [ ]:
# Evaluate on test set
y_test_pred = model.predict(x_test_tfidf)
test_accuracy = accuracy_score(y_test_encoded, y_test_pred)
print(f'Test Accuracy: {test_accuracy:.4f}')

Test Accuracy: 0.4266

In [ ]:
from sklearn.metrics import classification_report

# Get full label range
labels = list(range(len(label_encoder.classes_)))
target_names = label_encoder.classes_

# Print classification report
print(classification_report(
    y_test_encoded,
    y_test_pred,
    labels=labels,
    target_names=target_names,
    zero_division=0  # Avoids division-by-zero warnings
))

                                   precision    recall  f1-score   support

                         Egyptian       0.08      0.39      0.13       305
                           Hijazi       0.38      0.37      0.38      5225
                            Iraqi       0.00      0.00      0.00         0
                           Janubi       0.01      0.13      0.01        15
                          Khaliji       0.27      0.36      0.31      4274
                        Levantine       0.06      0.37      0.10       142
                         Maghrebi       0.03      0.17      0.05         6
             ModernStandardArabic       0.20      0.63      0.30       614
More than 1 speaker اكثر من متحدث       0.60      0.61      0.60      7520
                            Najdi       0.73      0.40      0.51     13599
                    Notapplicable       0.04      0.47      0.07        58
                          Shamali       0.01      0.16      0.02        19
                          Unknown       0.33      0.32      0.33      4441
                           Yemeni       0.02      0.19      0.03        57

                         accuracy                           0.43     36275
                        macro avg       0.20      0.33      0.20     36275
                     weighted avg       0.53      0.43      0.46     36275